### ISSUE TITLE
lib pyhessioc.cpython not found when current directory is pyhessio

### ISSUE THREAD

**Issue by jacquemier** [cta-observatory/pyhessio#5]
jacquem>cd pyhessio
 jacquem>python
 Python 3.5.cd pyt0 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:57:25) 
 [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
 Type "help", "copyright", "credits" or "license" for more information.
 >>> import pyhessio
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jacquem/workspace/CTA/pyhessio/pyhessio/__init__.py", line 27, in <module>
    lib = np.ctypeslib.load_library('pyhessioc', _path)
  File "/home/jacquem/anaconda3/lib/python3.5/site-packages/numpy/ctypeslib.py", line 128, in  load_library
    raise OSError("no file with expected extension")
 OSError: no file with expected extension
 >>> 
 jacquem>cd /tmp/
 jacquem>python
Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyhessio
>>>

**Comment by jacquemier** [comment]
The following command resolves this issue:

python setup.py develop
